import { Product, Category, Banner } from '../types';

export const categories: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    image: 'https://images.pexels.com/photos/1293120/pexels-photo-1293120.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    subcategories: [
      { id: 'mobiles', name: 'Mobiles' },
      { id: 'laptops', name: 'Laptops' },
      { id: 'audio', name: 'Audio' },
      { id: 'cameras', name: 'Cameras' },
    ],
  },
  {
    id: 'fashion',
    name: 'Fashion',
    image: 'https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    subcategories: [
      { id: 'men', name: "Men's Clothing" },
      { id: 'women', name: "Women's Clothing" },
      { id: 'kids', name: "Kids' Clothing" },
      { id: 'footwear', name: 'Footwear' },
    ],
  },
  {
    id: 'appliances',
    name: 'Appliances',
    image: 'https://images.pexels.com/photos/4108738/pexels-photo-4108738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    subcategories: [
      { id: 'tvs', name: 'Televisions' },
      { id: 'refrigerators', name: 'Refrigerators' },
      { id: 'washingMachines', name: 'Washing Machines' },
      { id: 'airConditioners', name: 'Air Conditioners' },
    ],
  },
  {
    id: 'grocery',
    name: 'Grocery',
    image: 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    subcategories: [
      { id: 'staples', name: 'Staples' },
      { id: 'snacks', name: 'Snacks & Beverages' },
      { id: 'household', name: 'Household Care' },
      { id: 'personal', name: 'Personal Care' },
    ],
  },
  {
    id: 'furniture',
    name: 'Furniture',
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    subcategories: [
      { id: 'living', name: 'Living Room' },
      { id: 'bedroom', name: 'Bedroom' },
      { id: 'dining', name: 'Dining' },
      { id: 'office', name: 'Office' },
    ],
  },
];

export const banners: Banner[] = [
  {
    id: '1',
    image: 'https://images.pexels.com/photos/5650026/pexels-photo-5650026.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    title: 'Big Saving Days',
    link: '/sale',
  },
  {
    id: '2',
    image: 'https://images.pexels.com/photos/5650025/pexels-photo-5650025.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    title: 'Electronics Sale',
    link: '/electronics',
  },
  {
    id: '3',
    image: 'https://images.pexels.com/photos/5632402/pexels-photo-5632402.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    title: 'Fashion Trends',
    link: '/fashion',
  },
];

export const products: Product[] = [
  {
    id: '1',
    title: 'iPhone 15 Pro (256GB)',
    description: 'A magical new way to interact with iPhone. Groundbreaking performance with A17 Pro. Game‑changing battery life. And a customizable Action button. All in titanium.',
    price: 999.99,
    originalPrice: 1199.99,
    discount: 17,
    rating: 4.7,
    reviews: 1458,
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/341523/pexels-photo-341523.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'electronics',
    brand: 'Apple',
    badge: 'New Launch',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Display', value: '6.1-inch Super Retina XDR display' },
      { name: 'Processor', value: 'A17 Pro chip' },
      { name: 'Camera', value: 'Pro camera system' },
      { name: 'Battery', value: 'Up to 23 hours video playback' },
      { name: 'Storage', value: '256GB' },
    ],
    features: [
      'Titanium design',
      'Action button',
      'USB-C connector',
      'iOS 17',
    ],
  },
  {
    id: '2',
    title: 'Samsung Galaxy S24 Ultra',
    description: 'Meet Galaxy S24 Ultra, the ultimate Galaxy AI phone with a built-in S Pen, our most powerful processor, and a stunning display.',
    price: 1199.99,
    originalPrice: 1399.99,
    discount: 14,
    rating: 4.6,
    reviews: 892,
    image: 'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'electronics',
    brand: 'Samsung',
    badge: 'Bestseller',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Display', value: '6.8-inch Dynamic AMOLED 2X display' },
      { name: 'Processor', value: 'Snapdragon 8 Gen 3' },
      { name: 'Camera', value: '200MP main camera' },
      { name: 'Battery', value: '5000mAh' },
      { name: 'Storage', value: '256GB' },
    ],
    features: [
      'S Pen included',
      'Galaxy AI features',
      'Water resistant (IP68)',
      'Android 14',
    ],
  },
  {
    id: '3',
    title: 'Sony WH-1000XM5 Noise Cancelling Headphones',
    description: 'Industry-leading noise cancellation with better call quality. Crystal clear hands-free calling with precise voice pickup.',
    price: 349.99,
    originalPrice: 399.99,
    discount: 13,
    rating: 4.8,
    reviews: 723,
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1591/technology-music-sound-things.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'electronics',
    brand: 'Sony',
    badge: 'Top Rated',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Type', value: 'Over-ear headphones' },
      { name: 'Battery Life', value: 'Up to 30 hours' },
      { name: 'Connectivity', value: 'Bluetooth 5.2' },
      { name: 'Weight', value: '250g' },
      { name: 'Charging', value: 'USB-C' },
    ],
    features: [
      'Industry-leading noise cancellation',
      'High-Resolution Audio',
      'Multipoint connection',
      'Speak-to-chat technology',
    ],
  },
  {
    id: '4',
    title: 'Dell XPS 15 Laptop',
    description: 'The XPS 15 features a stunning 15.6-inch 4K OLED display with InfinityEdge, the latest Intel Core processors, and NVIDIA GeForce RTX graphics.',
    price: 1899.99,
    originalPrice: 2199.99,
    discount: 14,
    rating: 4.5,
    reviews: 456,
    image: 'https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'electronics',
    brand: 'Dell',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Processor', value: 'Intel Core i9-12900HK' },
      { name: 'RAM', value: '32GB DDR5' },
      { name: 'Storage', value: '1TB SSD' },
      { name: 'Display', value: '15.6" 4K OLED' },
      { name: 'Graphics', value: 'NVIDIA GeForce RTX 3050 Ti' },
    ],
    features: [
      'Machined aluminum chassis',
      'Backlit keyboard',
      'Fingerprint reader',
      'Thunderbolt 4 ports',
    ],
  },
  {
    id: '5',
    title: 'Nike Air Max 270 Sneakers',
    description: 'The Nike Air Max 270 delivers visible air and unbelievable comfort. It features Nike\'s biggest heel Air unit yet, plus a super-soft foam forefoot for cushioning.',
    price: 129.99,
    originalPrice: 159.99,
    discount: 19,
    rating: 4.4,
    reviews: 928,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1895019/pexels-photo-1895019.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'fashion',
    brand: 'Nike',
    badge: 'Trending',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Material', value: 'Synthetic and mesh upper' },
      { name: 'Style', value: 'Lace-up closure' },
      { name: 'Cushioning', value: 'Max Air 270 heel unit' },
      { name: 'Outsole', value: 'Rubber' },
      { name: 'Fit', value: 'True to size' },
    ],
    features: [
      'Visible Max Air unit',
      'Breathable mesh upper',
      'Foam midsole',
      'Rubber outsole pods for durability',
    ],
  },
  {
    id: '6',
    title: 'Instant Pot Duo 7-in-1 Pressure Cooker',
    description: 'The Instant Pot Duo 7-in-1 is the most popular multi-cooker, combining 7 kitchen appliances in one: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer.',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    rating: 4.7,
    reviews: 1283,
    image: 'https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/5677794/pexels-photo-5677794.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/4958641/pexels-photo-4958641.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'appliances',
    brand: 'Instant Pot',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Capacity', value: '6 Quart' },
      { name: 'Functions', value: '7-in-1 Multi-cooker' },
      { name: 'Power', value: '1000 watts' },
      { name: 'Material', value: 'Stainless steel' },
      { name: 'Dimensions', value: '13.4 x 12.2 x 12.5 inches' },
    ],
    features: [
      '14 one-touch smart programs',
      'Customizable cooking settings',
      'Fingerprint-resistant stainless steel',
      'UL and ULC certified',
    ],
  },
  {
    id: '7',
    title: 'IKEA MALM Bed Frame',
    description: 'A clean design with solid wood veneer. The MALM bedroom series has a timeless look and practical function.',
    price: 249.99,
    originalPrice: 299.99,
    discount: 17,
    rating: 4.3,
    reviews: 582,
    image: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'furniture',
    brand: 'IKEA',
    inStock: true,
    freeDelivery: false,
    specifications: [
      { name: 'Size', value: 'Queen' },
      { name: 'Material', value: 'Wood veneer, particleboard' },
      { name: 'Color', value: 'Black-brown' },
      { name: 'Dimensions', value: '83 7/8 x 66 1/8 x 15 3/4 inches' },
      { name: 'Assembly', value: 'Required' },
    ],
    features: [
      'Adjustable bed sides for different mattress thicknesses',
      'Solid construction',
      'Slatted bed base included',
      'Storage boxes available separately',
    ],
  },
  {
    id: '8',
    title: 'Organic Fresh Fruits Basket',
    description: 'A fresh assortment of seasonal organic fruits. Perfect for a healthy lifestyle or as a thoughtful gift.',
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    rating: 4.6,
    reviews: 345,
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/8566526/pexels-photo-8566526.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    category: 'grocery',
    brand: 'Organic Farms',
    badge: 'Organic',
    inStock: true,
    freeDelivery: true,
    specifications: [
      { name: 'Weight', value: 'Approximately 5kg' },
      { name: 'Contents', value: 'Seasonal fruits (8-12 items)' },
      { name: 'Farming', value: 'Certified organic' },
      { name: 'Packaging', value: 'Eco-friendly' },
      { name: 'Shelf life', value: '7-10 days' },
    ],
    features: [
      'Pesticide-free',
      'Locally sourced when possible',
      'Hand-picked at peak ripeness',
      'Sustainably grown',
    ],
  },
];